### ISSUE TITLE
Add Faceboook Social Login

### ISSUE THREAD

**Issue by alvisanovari** [epilande/gatsby-theme-firebase#125]
Awesome job with this! Curious why you did not add Facebook in your social logins list? Is that something I can easily change?

**Comment by epilande** [comment]
Hey @alvisanovari definitely feel free to contribute! 

Here's a guideline for adding a provider:
1. Add the provider in [`gatsby-theme-firebase/src/firebase/auth/index.ts`](https://github.com/epilande/gatsby-theme-firebase/blob/master/gatsby-theme-firebase/src/firebase/auth/index.ts).
1. Add logo in [`gatsby-theme-firebase/src/components/icons/`](https://github.com/epilande/gatsby-theme-firebase/tree/master/gatsby-theme-firebase/src/components/icons)
1. Add auth button in [`<SocialLogins>`](https://github.com/epilande/gatsby-theme-firebase/blob/master/gatsby-theme-firebase/src/components/SocialLogins.tsx) component. 
1. Allow button to be toggled based on `socialLogins` setting from gatsby config. 

Let me know if you run into any problems

**Comment by alvisanovari** [comment]
Gotcha. Created a PR: https://github.com/epilande/gatsby-theme-firebase/pull/126

**Comment by epilande** [comment]
🎉 This has been released with [v1.0.8](https://github.com/epilande/gatsby-theme-firebase/releases/tag/v1.0.8)
