### ISSUE TITLE
Don't let users login unless they verify Email

### ISSUE THREAD

**Issue by alvisanovari** [epilande/gatsby-theme-firebase#152]
Currently - users are immediately logged in after they sign up without having to confirm the email via Firebase verification. Can we tweak the logic so that they need to verify? I believe Firebase has a Boolean field that indicates this.

**Comment by epilande** [comment]
Hi @alvisanovari 
I did a quick search and I wasn't able to find the boolean field you mentioned. 

Though I think this can be handled at the app level. Once a user logs in, you get a response with a `User` object which has a property `emailVerified`. 
https://firebase.google.com/docs/reference/js/firebase.User.html#emailverified 
Then render the appropriate route/page based on `emailVerified`.

**Comment by alvisanovari** [comment]
Yes - I solved it by using emailVerified. Similar to the protected route logic with isLoggedIn. Thanks!
