### ISSUE TITLE
Social login doesn't work in the demo

### ISSUE THREAD

**Issue by dandv** [epilande/gatsby-theme-firebase#230]
> "This domain (gatsby-theme-firebase.netlify.app) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab."

![image](https://user-images.githubusercontent.com/33569/80301690-ac90d200-87f9-11ea-8d62-cd49a9c88f76.png)

**Comment by epilande** [comment]
Thanks for the heads up! 
Updated my Firebase config and this should be working again
