### ISSUE TITLE
Extra file in the npm package

### ISSUE THREAD

**Issue by dandv** [epilande/gatsby-theme-firebase#233]
[components/social/GitHubButton.tsx](https://unpkg.com/browse/gatsby-theme-firebase@1.0.8/src/components/social/) is not [on GitHub](https://github.com/epilande/gatsby-theme-firebase/tree/master/gatsby-theme-firebase/src/components).

Package needs republishing?

**Comment by epilande** [comment]
Nice catch! I should really automate package publishing to avoid this in the future.

**Comment by epilande** [comment]
Resolved in [v1.0.10](https://github.com/epilande/gatsby-theme-firebase/releases/tag/v1.0.10).
